---
- hosts: all
  remote_user: root
  vars:
    compose_directory: /data/mt-mods-infra
  tasks:
    - name: Copy and template files
      template:
        src: "{{item}}"
        dest: "{{compose_directory}}/{{item}}"
      with_items:
        - "docker-compose.yml"
        - "config/matterbridge.toml"

    - name: Create nodered directory
      file:
        path: "{{compose_directory}}/data/nodered"
        state: directory
        owner: 1000
        group: 1000

    - name: Configure services
      docker_compose:
        project_src: "{{ compose_directory }}"
        pull: yes
        build: yes
        remove_orphans: yes
