version: '3.7'

services:
 matterbridge:
  image: 42wim/matterbridge:1.26.0
  volumes:
   - ./config/matterbridge.toml:/etc/matterbridge/matterbridge.toml
   - ./config/remotenickformat.tengo:/remotenickformat.tengo

 mt-mods-nodered:
  build: 
   dockerfile: ./Dockerfile.nodered
   context: ./
  restart: always
  networks:
   - terminator
   - default
  volumes:
   - "./data/nodered:/data"
   - "./config/nodered.js:/data/settings.js"
  labels:
   - "traefik.enable=true"
   - "traefik.docker.network=terminator"
   - "traefik.http.routers.mtmods.rule=Host(`mt-mods.minetest.ch`) && PathPrefix(`/nodered`)"
   - "traefik.http.services.mtmods.loadbalancer.server.port=1880"
   - "traefik.http.routers.mtmods.entrypoints=websecure"
   - "traefik.http.routers.mtmods.tls.certresolver=default"
  healthcheck:
   test: ['CMD','true']

 github-keepalive:
  build: 
   dockerfile: ./Dockerfile.keepalive
   context: ./
  restart: always
  environment:
   GITHUB_TOKEN: "{{ KEEPALIVE_GITHUB_TOKEN }}"
   GITHUB_REPOS: "minetest-game/repo_slicer minetest-mirrors/minetest-mirrors Archtec-io/archtec-infra"

networks:
 terminator:
  external: true
