[irc]
[irc.libera]
Server="irc.libera.chat:6667"
Nick="MTModsBot"
Password="{{ IRC_LIBERA_PASSWORD }}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
MessageSplit=true
EditSuffix=" (edited)"
ColorNicks=true

[discord]
[discord.mtmods]
Token="{{ DISCORD_MTMODS_TOKEN }}"
Server="905447873402003486"
UseUserName=false
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
AllowMention=["users"]

[matrix]
[matrix.mtmods]
Server="https://matrix.org"
Login="@mtmods:matrix.org"
Password="{{ MATRIX_MTMODS_PASSWORD }}"
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
NoHomeServerSuffix=true

[api.bot]
BindAddress="0.0.0.0:4243"
Buffer=1000
RemoteNickFormat="[{BRIDGE}] {NICK}"

[[gateway]]
name="main"
enable=true
[[gateway.inout]]
account="irc.libera"
channel="#mt-mods"
[[gateway.inout]]
account = "discord.mtmods"
channel="🛰modding"
[[gateway.inout]]
account = "matrix.mtmods"
channel="!IuYhGtsAusgKYlpUCs:matrix.org"
[[gateway.inout]]
account="api.bot"
channel="main"

[[gateway]]
name="offtopic"
enable=true
[[gateway.inout]]
account="irc.libera"
channel="#mt-mods-offtopic"
[[gateway.inout]]
account = "discord.mtmods"
channel="🏛lounge"
[[gateway.inout]]
account = "matrix.mtmods"
channel="!dQppybfdWYiNSoXjYP:matrix.org"
[[gateway.inout]]
account="api.bot"
channel="offtopic"

[[gateway]]
name="review-me"
enable=true
[[gateway.inout]]
account = "discord.mtmods"
channel="pls-review-me"
[[gateway.inout]]
account = "matrix.mtmods"
channel="!OdCHbjfdlIjUXXHqMC:matrix.org"
[[gateway.inout]]
account="api.bot"
channel="review-me"

[[gateway]]
name="tooling"
enable=true
[[gateway.inout]]
account = "discord.mtmods"
channel="🛠tooling"
[[gateway.inout]]
account = "matrix.mtmods"
channel="!NvhdxpOeVIwUQkaxos:matrix.org"
[[gateway.inout]]
account="api.bot"
channel="tooling"

[[gateway]]
name="bot"
enable=true
[[gateway.inout]]
account = "discord.mtmods"
channel="bot"
[[gateway.inout]]
account="api.bot"
channel="bot"
